### ISSUE TITLE
No database selected

### ISSUE THREAD

**Issue by bennewton999** [jekyll/jekyll-import#105]
I'm thinking that this is not directly a error with the importer, but when trying to import a WP .xml file, I am geting the following:

```
jekyll import wordpress   --source Squarespace.xml
Could not require 'htmlentities', so the :clean_entities option is now disabled.
error: Mysql2::Error: No database selected. Use --trace to view backtrace
```

This has me stumped.  Thanks.

**Comment by jaredcwhite** [comment]
thanks @bennewton999 and @parkr - your working through those issues helped me get a Squarespace -> Jekyll migration working! :)

**Comment by jaythanelam** [comment]
hi guys! I'm running into a similar issue I think, but certainly a newby when it comes to handling errors. here's what I get when I try to do the same import from squarespace xml file.

`Jaythans-MacBook-Pro:team-elam jaythanelam1$ ruby -rubygems -e 'require "jekyll-import"; JekyllImport::Importers::WordpressDotCom.run({ "source" => "wordpress.xml" })'
/Users/jaythanelam1/.rvm/gems/ruby-2.3.0/gems/jekyll-import-0.12.0/lib/jekyll-import/importers/wordpressdotcom.rb:61:in `text_for': undefined method `inner_text' for nil:NilClass (NoMethodError)
	from /Users/jaythanelam1/.rvm/gems/ruby-2.3.0/gems/jekyll-import-0.12.0/lib/jekyll-import/importers/wordpressdotcom.rb:157:in `block in process'
	from /Users/jaythanelam1/.rvm/gems/ruby-2.3.0/gems/jekyll-import-0.12.0/lib/jekyll-import/importers/wordpressdotcom.rb:145:in `each'
	from /Users/jaythanelam1/.rvm/gems/ruby-2.3.0/gems/jekyll-import-0.12.0/lib/jekyll-import/importers/wordpressdotcom.rb:145:in `process'
	from /Users/jaythanelam1/.rvm/gems/ruby-2.3.0/gems/jekyll-import-0.12.0/lib/jekyll-import/importer.rb:23:in `run'
	from -e:1:in `<main>'
`

**Comment by parkr** [comment]
The meat of the issue is:

    wordpressdotcom.rb:61:in `text_for': undefined method `inner_text' for nil:NilClass (NoMethodError)


This means that we're trying to access a method, `inner_text`, for an object that is `nil`. That's not good! It's likely a bug, or the SquareSpace exporter doesn't create an XML file that we know how to work with.
