### ISSUE TITLE
max_allowed_packet error on Drupal 7 import (Mysql::Error: Got packet bigger than 'max_allowed_packet' bytes)

### ISSUE THREAD

**Issue by rfay** [jekyll/jekyll-import#141]
Sorry, this seems like a stupid question, but I bumped my max_allowed_packet clear up to 1024M, verified the value with `SHOW VARIABLES LIKE "max_all%";` and I still get it. 

```
/Library/Ruby/Gems/2.0.0/gems/sequel-4.10.0/lib/sequel/adapters/mysql.rb:175:in `query': Mysql::Error: Got packet bigger than 'max_allowed_packet' bytes (Sequel::DatabaseError)
```

Stacktrace: https://gist.github.com/rfay/29fd0c5883de9a940473
System: MacOS Mavericks
DB: MariaDB 10
Command:
```
ruby -rubygems -e 'require "jekyll-import";
    JekyllImport::Importers::Drupal7.run({
      "dbname"   => "randyfay",
      "user"     => "root",
    })'
```

Suggestions?

**Comment by rfay** [comment]
Interestingly, I'm back to this same place 9 months later. Thinking it had something to do with my Mac/Homebrew environment, I built a new Ubuntu 14.04 VM so I could do it all there in a more "stock" environment. But I have exactly the same problem.

So AFAICT, this is related to the Drupal db. Note that it's quite common to have to increase max_allowed_packet with Drupal; it's the rule really. Nearly everybody needs 64M just for basic operations.

So... it appears that sequel/mysql2 isn't reading the standard config files (like /etc/mysql/my.cnf, ~/.my.cnf). Or if it is, it's using the values from an unknown section of the file. 

Does anybody know how to force this? Is it possible? Googling hasn't gotten me there. Thanks for your help.

**Comment by parkr** [comment]
Did you try `:default_file => '/path/to/myqsl/my.cf'`in the `Mysql2::Client` creation, or try setting that variable in the `:variables` hash?

http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/MysqlAdapter.html

**Comment by rfay** [comment]
Thanks for the followup... but where would I do that ? :-) I didn't know that there was any config of the Mysql2 client creation. And I *think* this is using mysql, not mysql2, at least that's the way it built on the linux version.

**Comment by parkr** [comment]
Configuring it by manually editing the gem when it creates the database: https://github.com/jekyll/jekyll-import/blob/master/lib/jekyll-import/importers/drupal7.rb#L49

I only see one mention as to how it can be configured: https://github.com/luislavena/mysql-gem/blob/master/ext/mysql_api/mysql.c#L205

**Comment by rfay** [comment]
Thanks for the response and help.

I tried setting :config_default_group => 'client' in the db open you pointed me to in drupal7.rb, which should hit a match on any of the files it might find, but I'm pretty sure it's not looking at any files. 

I don't know how to recompile mysql.c unfortunately. 

This is a pretty serious issue for both drupal importers since nearly any drupal site has to have max_packet_size set higher than the default. It's just standard folklore in the Drupal world.

**Comment by parkr** [comment]
I don't know what to do at this point. The MySQL client.

> I don't know how to recompile mysql.c unfortunately.

Go into the source of the gem and run `ruby ext/extconf.rb` or wherever that rb file is then, cd to where it dropped the makefile and run `make`.
