### ISSUE TITLE
Wordpress importer does not preserve permalinks.

### ISSUE THREAD

**Issue by pepijndevos** [jekyll/jekyll-import#164]
When I moved my blog from Posterous to Jekyll, the importer generated front matter like this:

```
permalink: /2009/08/nieuwe-website/index.html
```

After changing my domain name, all links continued to work. This is really important.

With the current WP importer, you just get the default link structure and all your links break.

**Comment by hfiguiere** [comment]
Yep, really missing. That's sad.

**Comment by parkr** [comment]
@hfiguiere I'd love to review a PR if you can write one!

**Comment by hfiguiere** [comment]
Now that I tried the wordpressdotcom importer (works fine on self hosted), my willingness to learn Ruby to fix it has dimnished greatly. Also that other importer doesn't choke on UTF-8. So it is full win.

**Comment by hfiguiere** [comment]
Actually I was wrong it doesn't import them either. It is just a fluke.

**Comment by parkr** [comment]
@hfiguiere: Make sure the permalink is [in this SQL query](https://github.com/jekyll/jekyll-import/blob/master/lib/jekyll-import/importers/wordpress.rb#L126) and gets added to [this hash](https://github.com/jekyll/jekyll-import/blob/master/lib/jekyll-import/importers/wordpress.rb#L284) and you're golden.

**Comment by fuzzy76** [comment]
So if this is still a problem, should I file a new issue? I would expect an imported site to have identical URLs. If not, your pagerank will really take a hit. :-(

**Comment by parkr** [comment]
@fuzzy76 If you can take a crack at fixing it, please do! Pretty simple procedural code 😄

**Comment by fuzzy76** [comment]
I think I'd rather go with https://wordpress.org/plugins/jekyll-exporter/ it seems to have much better exports...

**Comment by parkr** [comment]
Ok!
