### ISSUE TITLE
Standard for YAML front matter

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll-import#181]
As per jekyll/jekyll#3300, perhaps it would be a good idea to define a strict standard for representing imported metadata in YAML.

For instance, should a post `author` be a display name as a string, or should it be a hash that contains a `display_name`, `email`, `url`, etc.?

When these details are left to the discretion of the author of each importer, it makes it difficult to create a layout that correctly displays the author name given the wide variety of ways to represent such data.

**Comment by parkr** [comment]
:+1: 

Maybe start with the README, then apply the standards to each importer? Sometimes the data isn't available, sometimes it is.

**Comment by pathawks** [comment]
> Maybe start with the README, then apply the standards to each importer?

SGTM

> Sometimes the data isn't available, sometimes it is.

I think that's fine. The bigger issue is: *IF* the author's email address is available, it must be imported as `author.email`, or whatever.
