### ISSUE TITLE
Drupal7: Import author and other custom field values?

### ISSUE THREAD

**Issue by graemeduckett** [jekyll/jekyll-import#182]
Hey! I've run the importer successfully which gave me Front Matter for Title and Created variables, which made me realize I still need the author name, and ideally the path or at least the file name of a banner image that is set for each blog post.

I have limited Ruby knowledge so am wondering if there is a way to do this or if it has been tackled before.

**Comment by parkr** [comment]
This hasn't been tackled before to my knowledge. The Drupal 7 importer is here: https://github.com/jekyll/jekyll-import/blob/master/lib/jekyll-import/importers/drupal7.rb

Should be pretty easy. Add the author fetching to the SQL query and ensure it's put in the data hash: https://github.com/jekyll/jekyll-import/blob/master/lib/jekyll-import/importers/drupal7.rb#L74

**Comment by graemeduckett** [comment]
Thanks for the reply. I may have to have a poke at it tonight. It would seem I'd have to grab UIDs that are assigned to nodes and match them to the user IDs and names to come up with the respective author names since Drupal doesn't assign usernames to nodes.
