### ISSUE TITLE
Couldn't import the post because of it is written in Chinese(in Windows)?

### ISSUE THREAD

**Issue by zombiezlk** [jekyll/jekyll-import#183]
When I try to migrate my blog from Wordpress to jekyll, this happen:
![20150114125247](https://cloud.githubusercontent.com/assets/3966101/5734242/47ae742c-9bec-11e4-9b76-c61fa96ba7a5.png)
  I've try to run "chcp 65001" in the CMD terminal, but it didn't work. What can I do?

**Comment by parkr** [comment]
You'r running on Windows? Not sure. Maybe the `File.read` needs to set the encoding.

**Comment by zombiezlk** [comment]
Can you please tell me how to do that? I'm not familiar with Ruby.

**Comment by parkr** [comment]
`File.read(filename, { encoding: 'utf-8' })` might do the trick.

This requires changes to jekyll-import.

**Comment by zombiezlk** [comment]
I am using the WordPress.com importer, there is my code:
  ruby -rubygems -e 'require "jekyll-import";
    JekyllImport::Importers::WordpressDotCom.run({
      "source" => "wordpress.xml",
      "no_fetch_images" => false,
      "assets_folder" => "assets"
    })'
