### ISSUE TITLE
Wordpress Multisite

### ISSUE THREAD

**Issue by jk3us** [jekyll/jekyll-import#185]
In trying to import a single site that is part of a wordpress multisite instance, I had to make 1 small change in the source.  In my case, I wanted to import the site that had the database table prefix `3_` (the id of the site is 3), but since multisite installations share a common set of users, and they are stored in the unprefixed `users` table, I just had to remove the #{px} for the users table on [line 144 of `importers/wordpress.rb`](https://github.com/jekyll/jekyll-import/blob/master/lib/jekyll-import/importers/wordpress.rb#L144), and it seems to have worked well.  Having a configuration option that could handle this case would be pretty nice.

**Comment by parkr** [comment]
`--multisite`?

**Comment by jk3us** [comment]
Is that a command-line switch? I don't see that in any docs or in the code. How would that be used?

**Comment by parkr** [comment]
@jk3us I'm proposing it :) It'd do what you describe – use the specified table prefix except for the `users` table.

**Comment by jk3us** [comment]
Ah, sounds good.  You'd need a way to specify which site, I guess by numeric id.  I think you can have the installation prefix in addition to the site prefix, e.g. wp_3_posts.

**Comment by parkr** [comment]
@jk3us Hm, ok. I've never used a multisite before. Is the table prefix shared between them? So you have `prefix_num_table` and a separate `users` table?

**Comment by jk3us** [comment]
Looks like it, here is the code that returns the database table prefix for a site.  http://doc-wordpress.com/nav.html?wp-includes/wp-db.php.source.html#l727

**Comment by dirkkelly** [comment]
I have opened a pull request that will allow you to import specific sites from 3.4.2

https://github.com/jekyll/jekyll-import/pull/203
