### ISSUE TITLE
Drupal 5 Support

### ISSUE THREAD

**Issue by JoshuaRogers** [jekyll/jekyll-import#186]
Hi. I'm going to be modifying the D6 plugin in order to import a few old Drupal 5 sites. I was wondering if there would be any interest in me adding a pull request.

**Comment by parkr** [comment]
Do it up! Drupal 5 was once a thing. Also, if you find any way to make these drupal importers common, that'd also be cool. There isn't *much* that changed if I'm remembering the Drupal 6 -> 7 importers correctly.

**Comment by rac2030** [comment]
I tested the drupal 6 exporter with a drupal 5 installation and it seems to work. At least for the standard types.
