### ISSUE TITLE
WordPress importer doesn't run (undefined local variable or method `jekyll' for main:Object)

### ISSUE THREAD

**Issue by rally25rs** [jekyll/jekyll-import#187]
I'm probably just missing something, but on Windows, Ruby 1.9.3, gem 1.8.29, jekyll 2.5.3, jekyll-import 0.5.3.

Command:

```
ruby -rubygems -e 'require "jekyll-import";
     JekyllImport::Importers::WordpressDotCom.run({
       "source" => "site.xml",
       "no_fetch_images" => false,
       "assets_folder" => "assets"
     })'
```

results in:

```
-e:1:in `<main>': undefined local variable or method `jekyll' for main:Object (NameError)
```

**Comment by rally25rs** [comment]
It seems that putting the code into an actual .rb file and running that does work.
Must just be a quirk of multi-line statements on windows command line.

**Comment by parkr** [comment]
Glad you got it figured out!
