### ISSUE TITLE
RSS importer fails to import Atom files

### ISSUE THREAD

**Issue by matthewmcvickar** [jekyll/jekyll-import#194]
I have an XML file of an Atom feed that passes validation.

I run the following: 

```sh
$ jekyll import rss --source atom.xml --trace
```

And get the following error:

```
/Users/matthewmcvickar/.rvm/gems/ruby-2.1.5/gems/jekyll-import-0.6.0/lib/jekyll-import/importers/rss.rb:36:in `process': There doesn't appear to be any RSS items at the source (atom.xml) provided. (RuntimeError)
	from /Users/matthewmcvickar/.rvm/gems/ruby-2.1.5/gems/jekyll-import-0.6.0/lib/jekyll-import/importer.rb:23:in `run'
	from /Users/matthewmcvickar/.rvm/gems/ruby-2.1.5/gems/jekyll-import-0.6.0/lib/jekyll-import.rb:30:in `block (3 levels) in add_importer_commands'
	from /Users/matthewmcvickar/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/matthewmcvickar/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/matthewmcvickar/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/matthewmcvickar/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/matthewmcvickar/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/matthewmcvickar/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/matthewmcvickar/.rvm/gems/ruby-2.1.5/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /Users/matthewmcvickar/.rvm/gems/ruby-2.1.5/bin/jekyll:23:in `load'
	from /Users/matthewmcvickar/.rvm/gems/ruby-2.1.5/bin/jekyll:23:in `<main>'
	from /Users/matthewmcvickar/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/matthewmcvickar/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by parkr** [comment]
Looks like it can't create an `RSS::Parser` for ya:

https://github.com/jekyll/jekyll-import/blob/8cd85763cea9a612f821d0f861b99ec1884ce491/lib/jekyll-import/importers/rss.rb#L33-L34

**Comment by matthewmcvickar** [comment]
@parkr Why is that happening, though? I believe the RSS parser handles Atom, not just RSS. The Atom file is passing feed validation.

**Comment by parkr** [comment]
@matthewmcvickar Can you send me your Atom file? Or can you dig into walking through this code? I don't know why it's not working because the RSS parser isn't throwing an error.

**Comment by matthewmcvickar** [comment]
@parkr Emailed you the file.

**Comment by parkr** [comment]
@matthewmcvickar I think I have a fix. Can you try modifying your gem source for the above, or testing with a clone of this repo at the specified branch?

**Comment by matthewmcvickar** [comment]
The import is starting now, but failing like #158 because the Atom file specifies no `date` field. Turns out that's not the only difference between Atom and RSS though—the post content is found in the `content` field (in RSS it's `description`), and I think categories are done differently too.

So… I'm not sure what's better, then: changing the parser to look for different fields depending on the type of feed, or make a separate Atom parser?

**Comment by parkr** [comment]
> So… I'm not sure what's better, then: changing the parser to look for different fields depending on the type of feed, or make a separate Atom parser?

I'd probably just modify this one. You should be able to determine whether it's straight-up RSS or Atom and just ask for the proper field based on the parser type or whatever.

**Comment by parkr** [comment]
You could also have 3 different methods, one that handles RSS, one Atom, and one the common fields.

**Comment by matthewmcvickar** [comment]
Sounds like a plan. I'll take a stab at forking this at some point.

**Comment by parkr** [comment]
:+1:
