### ISSUE TITLE
WordPress importer 'date' value can cause Jekyll build bugs

### ISSUE THREAD

**Issue by groovecoder** [jekyll/jekyll-import#200]
I used `jekyll-import` to convert a WordPress blog into a Jekyll site. `jekyll-import` gave one of the _posts a `date` value: `2013-01-07 22:17:23 -0600` and a `date_gmt` value: `2013-01-08 04:17:23 -0600`. (Separate bug?: the date_gmt value includes  the `-0600` timezone offset)

[Creating a post with a `date` value different from the date expressed in the post's filename causes build errors in (some versions of) `jekyll` and `safe_yaml`](https://github.com/jekyll/jekyll/pull/1886).

The jekyll importer needs to check for date differences between `date` and `date_gmt` values and be sure to create the filename with the same date value as the `date` front-matter data.

**Comment by parkr** [comment]
What was the build error you saw?

**Comment by groovecoder** [comment]
I couldn't actually get it, because it only happened on GitHub Pages - i.e., not my local environment. :cry:

**Comment by parkr** [comment]
@groovecoder If you write into support@github.com, they can look that up for you!

**Comment by groovecoder** [comment]
Oh, yeah, that had given this to me:
```
Liquid Exception: Could not find post "2013-01-07-packaged-html5-apps-are-we-emulating-failure" in tag 'post_url'. Make sure the post exists and the name is correct. in _layouts/post.html
```

**Comment by parkr** [comment]
We should include the timezone for sure in the `date`. In Jekyll 3, the `post_url` uses the slug from your `_posts` folder instead of a parsed date comparison.
