### ISSUE TITLE
Tumblr: Distill tags and normalize

### ISSUE THREAD

**Issue by shellscape** [jekyll/jekyll-import#201]
The tumblr importer works very well for basic data. However, it's pretty dumb with regard to tags in the sense that it doesn't care how the tags are defined (case, spacing, etc) - it'll plop them into front matter exactly how they're defined. That's fine for tumblr, but not for Jekyll. Jekyll considers tags of different case and spacing to be different tags. Tumblr on the other hand, does not. 

I'd love to see an option for normalizing tags on import (upper, lower, capitalized). I've written an exhaustive node script to handle this after import, but seems like that would be better suited to the importer itself.

**Comment by parkr** [comment]
Not a bad idea! We could also import everything and resolve "conflicts" in a prompt.

**Comment by shellscape** [comment]
:+1:  That'd be outstanding!
