### ISSUE TITLE
Tumblr: Carry over post author

### ISSUE THREAD

**Issue by shellscape** [jekyll/jekyll-import#202]
Tumblr posts are authored and represented by the tumblr username of the author. I'd like to see an option for the importer to include that data in `author:` or `tumblr_author:` so that further operations in Jekyll can be performed. Using a yml file in `_data` we could easily map old tumblr usernames to actual names. This is prevalent on organization blogs where there are multiple authors.

**Comment by parkr** [comment]
Works for me! PR it!

**Comment by shellscape** [comment]
@parkr alas, I don't ruby.

**Comment by parkr** [comment]
Not right now, but perhaps today's the day! If you program, I bet you you can Ruby :)
