### ISSUE TITLE
Drupal 6 content types

### ISSUE THREAD

**Issue by alehandrof** [jekyll/jekyll-import#206]
The Drupal 6 importer worked fine for importing stories, but it didn't import pages or panels. Is there any option or method of importing content besides stories? The site I'm working on also has some custom content types. Is there any hope for these?

**Comment by parkr** [comment]
AFAIK, not from the importers directly. Custom types are perfect for our Collections feature, but it all has to be manual from Drupal for that stuff at the moment.

**Comment by alehandrof** [comment]
Cheers. Thanks for taking a look.
