### ISSUE TITLE
Documentation is not clear

### ISSUE THREAD

**Issue by kamlekar** [jekyll/jekyll-import#207]
I am newb to ruby. I am struggling here to import wordpress posts to jekyll.

I already exported wordpress posts to an xml file, but now I am not able understand how to import that xml in my jekyll blog using this plugin.

I checked this [article](http://import.jekyllrb.com/docs/wordpress/), which hasn't mentioned where to write that big code. I assumed I should write in the ruby command prompt by `cd my-blog-folder`, which isn't working.

I am getting the following error:

      -e:1: syntax error, unexpected '=', expecting tASSOC 

Someone raised the same issue on [Stackoverflow](http://stackoverflow.com/q/25135219/1577396)

--

I am on Windows 8, Ruby 1.9.2

**Comment by parkr** [comment]
Whoa! That's an old version of Ruby. Does Ruby 1.9.2 have the hash rockets, i.e. `=>`?

**Comment by parkr** [comment]
A quick solution would be to upgrade to a newer version of Ruby, 1.9.3 or greater. We don't support anything before 2.0 anymore so I'm going to close this ticket. Ruby DevKit for Windows should help.

**Comment by kamlekar** [comment]
For future users, I already fixed it. Please refer the following [link](http://stackoverflow.com/a/31217105/1577396)
