### ISSUE TITLE
Tumblr import: URL not found

### ISSUE THREAD

**Issue by kristofvanlandschoot** [jekyll/jekyll-import#219]
I seem to get an error on my tumblr import:

Fetching http://coin-c.tumblr.com//api/read/json/?num=50&start=0
/Users/kristof/homebrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/open-uri.rb:358:in `open_http': 404 Not Found (OpenURI::HTTPError)

Should I enable something in tumblr? Or have they changed the API?

Thanks,
Kristof

**Comment by parkr** [comment]
Maybe they changed the api. Hmmm.

**Comment by parkr** [comment]
https://www.tumblr.com/docs/en/api/v1

**Comment by kristofvanlandschoot** [comment]
Got it. The double slash was the problem. Enhancement request: allow trailing slashes in the URL.

**Comment by parkr** [comment]
Oh interesting!

If you have time for a PR to create a `URI` from the input, I'll merge and release!
