### ISSUE TITLE
Update import instructions on http://import.jekyllrb.com.

### ISSUE THREAD

**Issue by antonio-gil** [jekyll/jekyll-import#226]
As the title says, I think that the information located on http://import.jekyllrb.com need to be updated to reflect on how the import is made (at least with blogger, the platform from which I was doing the import).

On that site, the instructions say that the import is made with the following code:

```bash
$ ruby -rubygems -e 'require "jekyll-import";
JekyllImport::Importers::Blogger.run({
"source"                => "/path/to/blog-MM-DD-YYYY.xml",
"no-blogger-info"       => false, # not to leave blogger-URL info (id and old URL) in the front matter
"replace-internal-link" => false, # replace internal links using the post_url liquid tag.
})'
```

But, by doing the import in that way I was having an issue (`-e:1: syntax error, unexpected '=', expecting =>`). the way in that I could made the importation was using the command that you mention on this repository (`jekyll import IMPORTER [options]`).

By the way, I'm using [PortableJekyll](https://github.com/madhur/PortableJekyll) (it comes with **ruby 2.0.0p247**, **jekyll 3.0.0**, and **jekyll-import (0.8.0)**) on a Windows 10 x64 machine.

Thanks in advance.

**Comment by parkr** [comment]
I do not get that issue with jekyll-import v0.9.0. Could you try with this latest version of Jekyll-import?

```text
~$ ruby -rubygems -e 'require "jekyll-import";
JekyllImport::Importers::Blogger.run({
"source"                => "/path/to/blog-MM-DD-YYYY.xml",
"no-blogger-info"       => false, # not to leave blogger-URL info (id and old URL) in the front matter
"replace-internal-link" => false, # replace internal links using the post_url liquid tag.
})'
/usr/local/var/rbenv/versions/2.1.7-github1/lib/ruby/gems/2.1.0/gems/jekyll-import-0.9.0/lib/jekyll-import/importers/blogger.rb:14:in `validate': No such file or directory - File not found: /path/to/blog-MM-DD-YYYY.xml (Errno::ENOENT)
	from /usr/local/var/rbenv/versions/2.1.7-github1/lib/ruby/gems/2.1.0/gems/jekyll-import-0.9.0/lib/jekyll-import/importer.rb:22:in `run'
	from -e:2:in `<main>'
```
