### ISSUE TITLE
Getting an error with wordpress import

### ISSUE THREAD

**Issue by pastorryanhayden** [jekyll/jekyll-import#229]
Hi,
I'm having the hardest time getting wordpress importer to work.  Here is the error:
     /Users/ryanhayden/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': LoadError: dlopen(/Users/ryanhayden/.rvm/gems/ruby-2.2.1/gems/mysql2-0.4.1/lib/mysql2/mysql2.bundle, 9): Library not loaded: libmysqlclient.18.dylib (Sequel::AdapterNotFound)
  Referenced from: /Users/ryanhayden/.rvm/gems/ruby-2.2.1/gems/mysql2-0.4.1/lib/mysql2/mysql2.bundle
  Reason: image not found - /Users/ryanhayden/.rvm/gems/ruby-2.2.1/gems/mysql2-0.4.1/lib/mysql2/mysql2.bundle

I've tried running
     gem install mysql2 

But it still throws the same error.  Any help would be awesome.

**Comment by parkr** [comment]
Do you have MySQL installed on your computer? The gem needs to access the C API that comes with it.

**Comment by pastorryanhayden** [comment]
I figured it out. Had to make a symlink (which I copied and pasted from another google search) to the instance of mysql I had on my mac already.  This worked fine afterwards.
