### ISSUE TITLE
Avoiding refresh layout/logic

### ISSUE THREAD

**Issue by sime** [jekyll/jekyll-import#241]
Hi,

I'm looking to import a Drupal 6 site and maintain the existing URL structure.

Looking at `drupal6.rb` the logic for meta refresh is pretty baked in.

I might be answering my own question, but the only way to avoid this logic is to create my own importer?

**Comment by parkr** [comment]
@sime Hi! 

> the only way to avoid this logic is to create my own importer? 

Unfortunately, yes. You can subclass from `Drupal6`, though, to make it a bit easier. Copy over `self.process`, rewrite what you don't like and go forth.

This importer needs a lot of love. If you're willing to send a PR, I'd be willing to look at it.

Thanks!
