### ISSUE TITLE
TextPattern Importer went (very) well. But where are the post categories? 

### ISSUE THREAD

**Issue by massimopinto** [jekyll/jekyll-import#250]
Hello,

I just imported my old texpattern-based blog posts, and it was rather exciting to see it all come back to life after many years sitting into a database. 
I am curious about the import process of database tables other than _textpattern_, such as the _category_ table, which is linked to the _Category_ variable of the _textpattern_ table. Is this open for development or it's a matter of (me) studying how to get this going?
Yours,
Massimo

**Comment by massimopinto** [comment]
I understand there was not traffic on this topic. But is there a solution anywhere?

**Comment by parkr** [comment]
Hey @massimopinto! Looks like the comment didn't post properly for the stale label.

The [TextPattern import code is all here](https://github.com/jekyll/jekyll-import/blob/master/lib/jekyll-import/importers/textpattern.rb). It doesn't look like it implements post categories. Want to take a crack at it?

**Comment by massimopinto** [comment]
That would be good fun. I will give it a try as soon as I complete another
task.
Cheers
Massimo

Massimo Pinto
ENEA, C.R. Casaccia
Department of Fusion and Technology for Nuclear Safety and Security
National Institute of Ionizing Radiation Metrology
Standards for protection-level dosimetry unit
http://www.inmri.enea.it/  (under maintenance)
=========================================
http://massimopinto.github.io

2016-07-07 2:50 GMT+02:00 Parker Moore <notifications@github.com>:

**Comment by massimopinto** [comment]
HI @parkr, I am going back to this old issue: I took a look at the code and it does not look that hard to tackle, to me. However, I am not sure what is the best way to proceed when importing comments that are associated to a blog post. Should they be inserted at the bottom of the main text, with a _static_ format? For jekyll sites maintained on GitHub Pages, I understand that one way to allow comments is to divert them to an external service such as Disqus. 
Yours
Massimo

**Comment by parkr** [comment]
> Should they be inserted at the bottom of the main text, with a static format?

For historical comments, this is a possibility. Alternatively, create a data file for each post like `_data/2016-01-02-my-old-post.yml` which contains an array of data you can pull in. Then in the layout or in an include, do something like:

```liquid
{% if site.data[post.id] %}
{% for comment in site.data[post.id] %}
  On {{ comment.date | date_to_sentence_string }}, {{ comment.author}} said:
  {{ comment.body }}
{% endfor %}
{% endif %}
```
