### ISSUE TITLE
Tumblr Import LoadError

### ISSUE THREAD

**Issue by benpetty** [jekyll/jekyll-import#279]
Not sure what I'm doing wrong. Entering this into terminal: 

`ruby -rubygems -e 'require "jekyll-import"; JekyllImport::Importers::Tumblr.run({ "url" => "http://audeos.tumblr.com", "format" => “md”, "grab_images" => true, "add_highlights" => false, "rewrite_urls" => false })'`

returns this: 

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- jekyll-import (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by parkr** [comment]
Did you run `sudo gem install jekyll-import`?

**Comment by benpetty** [comment]
Oh jeez, yes that was it. Thanks!

**Comment by parkr** [comment]
No problem!
