### ISSUE TITLE
Broken link on wordpress.com importer page

### ISSUE THREAD

**Issue by ramonsuarez** [jekyll/jekyll-import#293]
The link to "A great article" on the page http://import.jekyllrb.com/docs/wordpressdotcom/ is broken. I think the correct new link is https://vitobotta.com/2011/03/28/migrating-from-wordpress-to-jekyll-part-2-everything-you-need-to-know/

**Comment by pathawks** [comment]
Mind submitting a PR?

**Comment by ramonsuarez** [comment]
I would love to, but I have not found the page file to submit to, sorry :(

**Comment by pathawks** [comment]
https://github.com/jekyll/jekyll-import/blob/master/docs/_importers/wordpressdotcom.md

**Comment by ramonsuarez** [comment]
Done! :)

**Comment by Ryuno-Ki** [comment]
https://vitobotta.com/2011/03/28/migrate-from-wordpress-to-jekyll/ is the most recent location. Could somebody reopen this issue? Or shall I fill a new one?

**Comment by DirtyF** [comment]
fixed in https://github.com/jekyll/jekyll-import/commit/00a97b5cffcf0c4ca08884197fbc27408042fe6a
