### ISSUE TITLE
S9Y database importer does not take full post

### ISSUE THREAD

**Issue by judebert** [jekyll/jekyll-import#320]
OSX 10.11.6, Ruby 2.4.1p111, JekyllImport::Importers::S9YDatabase

S9Y supports excerpts and extended bodies. The importer does not include the extended body in the posts.

**Comment by parkr** [comment]
Hey! I think https://github.com/jekyll/jekyll-import/pull/299 will fix that for you – it pulls out a field called `entries.extended`. Please try jekyll-import v0.13.0. 😄
