### ISSUE TITLE
import blogger issue

### ISSUE THREAD

**Issue by krisrice** [jekyll/jekyll-import#321]
more migrate.sh 
ruby -rubygems -e 'require "jekyll-import";
    JekyllImport::Importers::Blogger.run({
      "source"                => "blog-09-20-2017.xml",
      "no-blogger-info"       => false, # not to leave blogger-URL info (id and old URL) in the front matter
      "replace-internal-link" => true, # replace internal links using the post_url liquid tag.
    })'

dhcp-10-149-251-225:blog klrice$ bash migrate.sh 
/usr/local/lib/ruby/gems/2.4.0/gems/jekyll-import-0.12.0/lib/jekyll-import/importers/blogger.rb:196:in `initialize': No such file or directory @ rb_sysopen - _drafts/2015-05-29-http://goo.gl/t04mxz.html (Errno::ENOENT)
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-import-0.12.0/lib/jekyll-import/importers/blogger.rb:196:in `open'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-import-0.12.0/lib/jekyll-import/importers/blogger.rb:196:in `tag_end'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rexml/parsers/streamparser.rb:36:in `parse'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-import-0.12.0/lib/jekyll-import/importers/blogger.rb:49:in `block in process'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-import-0.12.0/lib/jekyll-import/importers/blogger.rb:47:in `open'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-import-0.12.0/lib/jekyll-import/importers/blogger.rb:47:in `process'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-import-0.12.0/lib/jekyll-import/importer.rb:23:in `run'
	from -e:2:in `<main>'

**Comment by krisrice** [comment]
Issue is/was I had blog titles with / in them which is a dir separator so the create file failed. Probably need a escape/scrubber that deals with it.

**Comment by pathawks** [comment]
Can you post the XML you were trying to import, or a minimal example that fails?

I don't understand. It seems like we're trying to use the filename rather than title to create the file:
https://github.com/jekyll/jekyll-import/blob/24644fbb5c5dd57c21343cc867680c576e33098a/lib/jekyll-import/importers/blogger.rb#L195

**Comment by krisrice** [comment]
the issue is maybe that the line above is doing a 
                file_name = URI::decode("#{post_data[:filename]}.html")
so the :filename that has an escaped / in it is being unescaped back to having a / which will fail to make a file.

I had several blog titles that had things like : Debugging w/SQLDEV

That / would cause a fail once I went back and changed them to use "with" and removed the / it worked as planned.

**Comment by pathawks** [comment]
But the Blogger URL surely stripped the slash entirely, correct?

**Comment by krisrice** [comment]
Oh the problem is maybe then these were all Drafts and not published so maybe blogger doesn't scrub then until they are published.

**Comment by pathawks** [comment]
@krisrice Ok, that makes sense! I guess we can't rely on Blogger to always scrub illegal characters for us.

**Comment by krisrice** [comment]
Once that was fixed the importer worked awesome great job ! 
http://krisrice.io

**Comment by parkr** [comment]
Is there a pull request to fix this?
