### ISSUE TITLE
MySQL import port feature in docs but not yet released.

### ISSUE THREAD

**Issue by criztovyl** [jekyll/jekyll-import#325]
This is confusing, especially because it's in [the official(?) docs](http://import.jekyllrb.com/docs/wordpress/).

**Comment by criztovyl** [comment]
feature introduced in #311, docs updated by #312.

**Comment by criztovyl** [comment]
By released I mean the feature is not included in the lastest available Gem release ([`v0.12.0`](https://rubygems.org/gems/jekyll-import)).

Anyway, it really looks like your GH-pages config is broken: In the `gh-pages` branch the feature is not yet included in the docs, only in `master` so you seem to build the pages from `master`, which, as you have `gh-pages` does not seem like it's what you want?

**Comment by DirtyF** [comment]
We should probably release a new version of the gem, thanks for the reminder.

And yes we do build the docs from the `docs` folder on the `master` branch now, so `gh-pages` doesn't reflect the latest docs and could probably be deleted now.

**Comment by criztovyl** [comment]
> [...] so `gh-pages` doesn't reflect the latest docs and could probably be deleted now.

I have to object: `gh-pages` is identical to `v.0.12.0` and this way is latest: It's the latest available version.

I think it's not good to put the bleeding-edge docs from master to the official webpage: It only creates confusion if a feature like this is in the docs but not in the latest released version.

**Comment by DirtyF** [comment]
I guess we could continue to serve docs from `gh-pages` and update it every time there is a release, but most importantly we could release more often, e.g. they are [44 unreleased commits since `0.12`](https://github.com/jekyll/jekyll-import/compare/v0.12.0...master).

**Comment by DirtyF** [comment]
[Version `0.13` has been released](https://github.com/jekyll/jekyll-import/releases/tag/v0.13.0) 🎉

**Comment by criztovyl** [comment]
:+1:
