### ISSUE TITLE
Error installing jekyll-import

### ISSUE THREAD

**Issue by inwardmovement** [jekyll/jekyll-import#337]
I installed Jekyll on Windows the recommended way (using bash Ubuntu), and when trying to install jekyll-import I have this error (exerpts) :

```
ERROR:  Error installing jekyll-import:
ERROR: Failed to build gem native extension.
zlib is missing; necessary for building libxml2
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.
```

Are there special steps to make it work on Windows?

**Comment by SuriyaaKudoIsc** [comment]
You should run `sudo apt-get install zlib1g-dev` in Windows Bash Ubuntu.

**Comment by inwardmovement** [comment]
Thanks, it seem to work!
