### ISSUE TITLE
Error when importing from drupal 7 using v.0.14

### ISSUE THREAD

**Issue by ccamara** [jekyll/jekyll-import#340]
Disclaimer: I am a newbie to jekyll (I've used in a couple of simple sites) and to ruby. 

I wanted to migrate from a drupal 7 site and haven't been able to do it despite I think I've been following the instructions.

That's what I've done so far:

1. Update jekyll-import to v.0.14
1. Create a blank jekyll site (`jekyll new myblog`)
2. Navigate to `myblog` site.
3. Run the following code:
```

$ ruby -rubygems -e 'require "jekyll-import";
    JekyllImport::Importers::Drupal7.run({
      "dbname"   => "name",
      "user"     => "myuser",
      "password" => "mypassword",
      "host"     => "myhost",
      "prefix"   => "mytableprefix",
      "types"    => ["blog", "post"]
    })'
```
(obviously I replaced my database name, user, password, host, prefix and types).

Unfortunately I get the following error, which is different from the [previous one](https://github.com/jekyll/jekyll-import/issues/334):

```
/var/lib/gems/2.3.0/gems/jekyll-import-0.14.0/lib/jekyll-import/importers/drupal_common.rb:45:in `fetch': key not found: "engine" (KeyError)
        from /var/lib/gems/2.3.0/gems/jekyll-import-0.14.0/lib/jekyll-import/importers/drupal_common.rb:45:in `process'
        from /var/lib/gems/2.3.0/gems/jekyll-import-0.14.0/lib/jekyll-import/importer.rb:23:in `run'
        from -e:2:in `<main>'

```

Unfortunately, I cannot understand the error. What am I doing wrong?

**Comment by DirtyF** [comment]
What if you add the `engine`key (see #331)?

```
$ ruby -rubygems -e 'require "jekyll-import";
    JekyllImport::Importers::Drupal7.run({
      "engine"   => "mysql",
      "dbname"   => "name",
      "user"     => "myuser",
      "password" => "mypassword",
      "host"     => "myhost",
      "prefix"   => "mytableprefix",
      "types"    => ["blog", "post"]
    })'
```

**Comment by ccamara** [comment]
Yes! worked in a matter of seconds! Thank you very much!
