### ISSUE TITLE
ButterCMS -> Jekyll blog Importer

### ISSUE THREAD

**Issue by jkchilds** [jekyll/jekyll-import#342]

**Comment by DirtyF** [comment]
have you tried [generating a feed](https://buttercms.com/docs/api-client/ruby#BloggingRSSAtomSitemap)  and use the [RSS importer](http://import.jekyllrb.com/docs/rss/)?

**Comment by BerkhanBerkdemir** [comment]
Actually, I wanted to ask export from Hexo but I'll try this RSS importer. If I positive result I'll share with you.

**Comment by BerkhanBerkdemir** [comment]
I ran this command

```
ruby -rubygems -e 'require "jekyll-import"; JekyllImport::Importers::RSS.run({ "source" => "atom.xml" })'
```

```
/var/lib/gems/2.3.0/gems/jekyll-import-0.14.0/lib/jekyll-import/importers/rss.rb:41:in `block in process': undefined method `strftime' for nil:NilClass (NoMethodError)
from /var/lib/gems/2.3.0/gems/jekyll-import-0.14.0/lib/jekyll-import/importers/rss.rb:40:in `each'
from /var/lib/gems/2.3.0/gems/jekyll-import-0.14.0/lib/jekyll-import/importers/rss.rb:40:in `process'
from /var/lib/gems/2.3.0/gems/jekyll-import-0.14.0/lib/jekyll-import/importer.rb:23:in `run'
from -e:1:in `<main>'
```

@DirtyF  @pathawks Could you help me about that because I didn't figure it out.

**Comment by DirtyF** [comment]
Could you point to the URL of the feed?

**Comment by BerkhanBerkdemir** [comment]
https://blog.berkhanberkdemir.com/atom.xml
This feed has limit, 140 characters. I recreated new one in my local PC and I tried to use but I got an error.

**Comment by DirtyF** [comment]
@BerkhanBerkdemir yes please, open a dedicated issue (Import RSS from Hexo)
