### ISSUE TITLE
Error in WordPress importer

### ISSUE THREAD

**Issue by cobrafast** [jekyll/jekyll-import#368]
Getting the error `can't modify frozen String` from one of the SQL queries in the importer preventing me from using the importer entirely.

```
ruby -r rubygems -e 'require "jekyll-import"; JekyllImport::Importers::WordPress.run({"dbname"=>"***","user"=>"***","password"=>"***"})'
```

```
Traceback (most recent call last):
        2: from -e:1:in `<main>'
        1: from /var/lib/gems/2.5.0/gems/jekyll-import-0.15.0/lib/jekyll-import/importer.rb:25:in `run'
/var/lib/gems/2.5.0/gems/jekyll-import-0.15.0/lib/jekyll-import/importers/wordpress.rb:166:in `process': can't modify frozen String (FrozenError)
```

https://github.com/jekyll/jekyll-import/blob/e0783f185f4dd73c83a72fe6e8f7094fdaa8c47c/lib/jekyll-import/importers/wordpress.rb#L166

```
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```

**Comment by DirtyF** [comment]
@cobrafast sorry for that, published a fix.
In the meantime you can try to uninstall latest gem and use v0.14:

```
gem uninstall jekyll-import
gem nstall jekyll-import -v 0.14
```

**Comment by DirtyF** [comment]
Fixed in https://github.com/jekyll/jekyll-import/commit/e59a985665ecf10b5614a7fee1c2df98829a518c
