### ISSUE TITLE
convert MDwiki to jeky

### ISSUE THREAD

**Issue by mhdtouban** [jekyll/jekyll-import#375]
Hello,

Am looking to convert my MDwiki (http://dynalon.github.io/mdwiki/#!index.md) into jeky. How to use the Importers for that purpose?

Thanks,

**Comment by mattr-** [comment]
Assuming you're working with markdown files, there's no conversion from mdwiki to Jekyll. You'll need to create a new Jekyll site and add the markdown files from the wiki to it.
