### ISSUE TITLE
Is fastercsv even used?

### ISSUE THREAD

**Issue by dleidert** [jekyll/jekyll-import#422]
`mephisto.rb` references the fastercsv gem. But it actually seems to use `csv.rb` only and the latter uses the ruby csv class. Am I missing something?

**Comment by mattr-** [comment]
`fastercsv` was an external csv library which was then pulled into the Ruby Standard Library and just renamed to `csv`. If you want to submit a PR to fix that discrepancy, that'd be awesome.
