### ISSUE TITLE
plugin doesn't work - i get a black screen 

### ISSUE THREAD

**Issue by SabRenaEdpPdP** [jekyll/jekyll-import#463]
after taking a month for my host to unblock the jekyll export plugin which triggered the firewalll I finally managed to import it in wordrepss but it doesn't work. 
I get a black screen with no information or option to export anything whatsoever , my site is eclaireusedespossibles.com

**Comment by SabRenaEdpPdP** [comment]
sorry, have no idea where to find such script :( 
I just installed the zip file as an extension, and when I go to setting - jekyll export nothin happens

**Comment by ashmaroli** [comment]
What zip file?
What do you mean by `when I go to setting - jekyll export`?

**Comment by ashmaroli** [comment]
I think you may have confused this plugin with https://wordpress.org/plugins/jekyll-exporter/
The two plugins are different projects.
