### ISSUE TITLE
Problem extracting titles from Drupal 7 site

### ISSUE THREAD

**Issue by davad** [jekyll/jekyll-import#90]
I'm having this problem with 0.1.0.beta1.

All of the posts I export from my Drupal 7 blog end up with lines like this for the title metadata:
```yaml
title: !binary |-
  SGVsbG8gV29ybGQ=
```

To debug it, I added a 'puts title' after line 69 of the [Drupal 7 importer](https://github.com/jekyll/jekyll-import/blob/master/lib/jekyll-import/importers/drupal7.rb). 

It looks like it's extracting the title correctly from the Drupal database, but somehow it's not being written to the meta-data correctly. Any idea what's going on?

**Comment by antonizoon** [comment]
I have solved this issue in [this pull request.](https://github.com/jekyll/jekyll-import/pull/192)

For these pesky titles (such as those with stray `\xE2` junk that screws everything up), I applied `strip` and `force_encoding("UTF-8")` to the `title` string.

**Comment by parkr** [comment]
Fixed by #192.
